# -*- coding: utf-8 -*-
"""trabalho_car.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13ZGX2qlbW93W-G6AUwH0rKIfKPPFQNpf
"""

import torch, torchvision
from torchvision.transforms.functional import to_tensor
from torchvision.models.detection import fasterrcnn_resnet50_fpn_v2, FasterRCNN_ResNet50_FPN_V2_Weights
from PIL import Image, ImageDraw, ImageFont
import matplotlib.pyplot as plt
import numpy as np

device = "cuda" if torch.cuda.is_available() else "cpu"
weights = FasterRCNN_ResNet50_FPN_V2_Weights.COCO_V1
model = fasterrcnn_resnet50_fpn_v2(weights=weights).to(device).eval()
CATEGORIES = weights.meta["categories"]
VEHICLE = {"car", "truck", "bus", "motorcycle", "bicycle"}

def draw_boxes_pil(img: Image.Image, boxes, labels, scores, color=(0,255,0)):
    img = img.convert("RGB")
    draw = ImageDraw.Draw(img)
    try:
        font = ImageFont.truetype("DejaVuSans.ttf", 16)
    except:
        font = ImageFont.load_default()

    for (x1, y1, x2, y2), lab, sc in zip(boxes, labels, scores):
        draw.rectangle([x1, y1, x2, y2], outline=color, width=3)
        text = f"{lab} {sc:.2f}"

        bbox = draw.textbbox((x1, y1), text, font=font)
        tw, th = bbox[2] - bbox[0], bbox[3] - bbox[1]
        draw.rectangle([x1, y1 - th - 4, x1 + tw + 6, y1], fill=color)
        draw.text((x1 + 3, y1 - th - 2), text, fill=(0,0,0), font=font)
    return img

@torch.inference_mode()
def detect_vehicles_pil(pil_img: Image.Image, keep=("car",), conf_thr=0.35):
    keep_set = set(keep) if keep else VEHICLE
    t = to_tensor(pil_img.convert("RGB")).to(device)
    out = model([t])[0]
    boxes = out["boxes"].cpu().numpy()
    labels_idx = out["labels"].cpu().numpy()
    scores = out["scores"].cpu().numpy()

    kept_boxes, kept_labels, kept_scores, rows = [], [], [], []
    for box, lid, sc in zip(boxes, labels_idx, scores):
        if sc < conf_thr:
            continue
        name = CATEGORIES[int(lid)]
        if name in keep_set:
            x1,y1,x2,y2 = map(int, box.tolist())
            kept_boxes.append((x1,y1,x2,y2))
            kept_labels.append(name)
            kept_scores.append(float(sc))
            rows.append({"label": name, "confidence": round(float(sc), 3), "bbox_xyxy": [x1,y1,x2,y2]})

    annotated = draw_boxes_pil(pil_img.copy(), kept_boxes, kept_labels, kept_scores)
    return annotated, rows

def show_image(pil_img, title=""):
    plt.figure(figsize=(10,8))
    plt.imshow(pil_img)
    plt.axis("off")
    if title:
        plt.title(title)
    plt.show()

print("update image")

from google.colab import files
from PIL import Image
import matplotlib.pyplot as plt

KEEP = ("car", "truck", "bus")  # choose what you want to detect
CONF = 0.35  # confidence threshold

uploaded = files.upload()
for name in uploaded:
    img = Image.open(name)
    ann, rows = detect_vehicles_pil(img, keep=KEEP, conf_thr=CONF)

    print(f"\n{name} — {len(rows)} detections")
    for r in rows:
        print(r)

    # --- show side-by-side ---
    fig, ax = plt.subplots(1, 2, figsize=(14, 8))
    ax[0].imshow(img)
    ax[0].set_title("Original Image")
    ax[0].axis("off")

    ax[1].imshow(ann)
    ax[1].set_title(f"Detected Vehicles ({len(rows)})")
    ax[1].axis("off")

    plt.tight_layout()
    plt.show()